Source ./common.tape
Output vid.gif

Type "tenx --model gpt4o code ./src/main.rs"
Enter
Sleep 500ms
Type "iWrite a command-line tool that uses misanthropy to prompt Claude"
Enter
Type "to ask it how it feels, and prints the result."
Enter
Type "I've already added tokio and misanthropy to Cargo.toml."
Enter
Enter
Type "Read the API keys from the environment."

Sleep 500ms
Escape
Type ":wq"
Enter

Wait

Sleep 5s
